INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Bob', 'bob@gmail.com', '$qmNQB9TulhE3pxR7y8Rfbe/id9epWS89G8P0Xq1LgsV.fFtfYZ0w.');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Alex', 'alex@gmail.com', '$2a$10$UaRRPPPPEM9WPvHxRZGvnOibJruipPeU2Y7wdSoBX/P0YOwndsZnm');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Chris', 'chris@gmail.com', '$2a$10$j6bIHlohgKP2HD3y0xh9wOYPEm5hJa9SaGnnZvIVvaRRJno.0.moS');

INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_CLIENT');
INSERT INTO TB_ROLES (ROLE_NAME) VALUES ('ROLE_ADM');

INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);
